openapi: 3.0.0
info:
  title: Project API
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id: { type: string }
        username: { type: string }
        email: { type: string }
        avatar: { type: string, nullable: true }
        bio: { type: string, nullable: true }
    Post:
      type: object
      properties:
        id: { type: string }
        title: { type: string }
        content: { type: string }
        authorId: { type: string }
        spaceId: { type: string }
        createdAt: { type: string, format: date-time }
    Space:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        slug: { type: string }
        description: { type: string }
        image: { type: string, nullable: true }
    Notification:
      type: object
      properties:
        id: { type: string }
        userId: { type: string }
        type: { type: string, example: "post_like" }
        message: { type: string }
        isRead: { type: boolean }
        createdAt: { type: string, format: date-time }

paths:
  # --- AUTH ---
  /register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [username, email, password]
              properties:
                username: { type: string }
                email: { type: string }
                password: { type: string }
      responses:
        200: { description: OK }
  /login:
    post:
      summary: Login user
      tags: [Auth]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        200: { description: Returns tokens }
  /refresh-token:
    post:
      summary: Refresh access token
      tags: [Auth]
      responses:
        200: { description: OK }
  /verify-email:
    post:
      summary: Verify via POST
      tags: [Auth]
    get:
      summary: Verify via URL
      tags: [Auth]
  /me:
    get:
      summary: Current user profile
      tags: [Auth]
      security: [{ bearerAuth: [] }]
      responses:
        200:
          content:
            application/json:
              schema: { $ref: "#/components/schemas/User" }
  /logout:
    post:
      summary: Logout
      tags: [Auth]
      security: [{ bearerAuth: [] }]
  /account:
    delete:
      summary: Delete account
      tags: [Auth]
      security: [{ bearerAuth: [] }]

  # --- POSTS ---
  /posts:
    get:
      summary: List and filter posts
      tags: [Posts]
      parameters:
        - in: query
          name: page
          schema: { type: integer }
        - in: query
          name: sort
          schema: { type: string, enum: [new, top, hot] }
        - in: query
          name: spaceSlug
          schema: { type: string }
      responses:
        200: { description: List of posts }
    post:
      summary: Create a post
      tags: [Posts]
      security: [{ bearerAuth: [] }]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [title, content, spaceId]
              properties:
                title: { type: string }
                content: { type: string }
                spaceId: { type: string }
      responses:
        200: { description: Post created }

  /posts/images:
    post:
      summary: Upload multiple post images
      tags: [Posts]
      security: [{ bearerAuth: [] }]
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: array
                  items: { type: string, format: binary }
      responses:
        200: { description: List of Cloudinary URLs }

  /posts/{postId}:
    get:
      summary: Get post by ID
      tags: [Posts]
      parameters:
        [{ in: path, name: postId, required: true, schema: { type: string } }]
    put:
      summary: Edit post (Owner only)
      tags: [Posts]
      security: [{ bearerAuth: [] }]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                content: { type: string }
    delete:
      summary: Delete post
      tags: [Posts]
      security: [{ bearerAuth: [] }]

  /posts/{postId}/vote:
    post:
      summary: Upvote, Downvote or Clear vote
      tags: [Posts]
      security: [{ bearerAuth: [] }]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type: { type: string, enum: [upvote, downvote, none] }

  /posts/{postId}/save:
    post:
      summary: Save post
      tags: [Posts]
      security: [{ bearerAuth: [] }]

  /posts/{postId}/comments:
    get:
      summary: Get post comments
      tags: [Posts]
    post:
      summary: Add a comment
      tags: [Posts]
      security: [{ bearerAuth: [] }]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [content]
              properties:
                content: { type: string }
                parentId: { type: string }

  # --- SPACES ---
  /spaces:
    get:
      summary: List all spaces
      tags: [Spaces]
    post:
      summary: Create/Request a space
      tags: [Spaces]
      security: [{ bearerAuth: [] }]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [name]
              properties:
                name: { type: string }
                description: { type: string }
                image: { type: string }

  /spaces/images:
    post:
      summary: Upload space cover image
      tags: [Spaces]
      security: [{ bearerAuth: [] }]
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image: { type: string, format: binary }

  /spaces/{spaceId}/join:
    post:
      summary: Join a space
      tags: [Spaces]
      security: [{ bearerAuth: [] }]

  # --- USERS / PROFILE ---
  /users/{username}:
    get:
      summary: Get public profile
      tags: [Users]
  /users/update:
    put:
      summary: Update my profile
      tags: [Users]
      security: [{ bearerAuth: [] }]
  /users/avatar:
    post:
      summary: Upload avatar
      tags: [Users]
      security: [{ bearerAuth: [] }]
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar: { type: string, format: binary }

  # --- NOTIFICATIONS ---
  /notifications:
    get:
      summary: List notifications
      tags: [Notifications]
      security: [{ bearerAuth: [] }]
  /notifications/unread-count:
    get:
      summary: Get unread count
      tags: [Notifications]
      security: [{ bearerAuth: [] }]

  # --- TAGS ---
  /tags:
    get:
      summary: List all tags
      tags: [Tags]
